version: "3.3"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "your_password"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-db-system:/var/opt/mssql
      - mssql-db-data-files:/var/opt/sqlserver
# Names our volume
volumes:
 mssql-db-system:  
 mssql-db-data-files:  