version: '3.3'
services:
  mysql-db:
    container_name: mysql-server-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'php'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'your_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'your_password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db-data:/var/lib/mysql
# Names our volume
volumes:
 mysql-db-data: